version: "3"
services:  
  eazybuilder-web:
    build: ../eazybuilder-web/src/main/docker
    ports:
      - "30091:80"
    volumes:
     - ./nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf
     - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/logs:/var/log/nginx/
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
    networks:
     - eazybuilder

  eazybuilder-server:
    build:
      context: ../eazybuilder-server/pipeline/jenkins-client/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NACOS_IP=10.137.25.90
      - NACOS_PORT=8848      
      - NACOS_USER=nacos    
      - NACOS_PASSWORD=nacos   
      - NACOS_SPACE=pro         
    networks:
     - eazybuilder

networks:
  eazybuilder:
