#Rabbitmq的配置
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: /
    username: admin
    password: admin123
    #确认消息已发送到交换机exchange(开启手动确认消息)
    publisher-confirm-type: correlated
    #确认消息从exchange发送到queue
    publisher-returns: true 
    # 设置手动确认(ack)
    listener: 
      direct:
        acknowledge-mode: manual    
      simple: 
        acknowledge-mode: manual    
        prefetch: 200  #一次预加载消息的数量